// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Entities;

public partial class EmployeeMaster
{
    public int RowId { get; set; }

    public string EmployeeCode { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? CountryId { get; set; }

    public int? StateId { get; set; }

    public int? CityId { get; set; }

    public string EmailAddress { get; set; }

    public string MobileNumber { get; set; }

    public string PanNumber { get; set; }

    public string PassportNumber { get; set; }

    public string ProfileImage { get; set; }

    public byte? Gender { get; set; }

    public bool IsActive { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public DateOnly DateOfJoinee { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual City City { get; set; }

    public virtual Country Country { get; set; }

    public virtual State State { get; set; }
}